import { NextResponse } from 'next/server';
import path from 'path';
import fs from 'fs/promises';
import connect from '@/lib/mongoose';
import SectionModel from '@/models/Section';
import { requireAdmin } from '@/lib/adminAuth';

export async function POST() {
  const { error } = await requireAdmin();
  if (error) return error;

  if (process.env.NODE_ENV !== 'development') {
    return NextResponse.json(
      { error: 'Generate Section Enums is only allowed in development' },
      { status: 403 }
    );
  }

  try {
    await connect();
    const docs = await SectionModel.find({}).sort({ slug: 1 }).lean();
    const sections = docs.map((d) => ({
      id: d.slug,
      label: d.name,
      allowedActions: Array.isArray(d.allowedActions) ? d.allowedActions : [],
    }));

    const escape = (s: string) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    const lines = sections.map(
      (s) =>
        `  { id: '${escape(s.id)}', label: '${escape(s.label)}', allowedActions: [${s.allowedActions.map((a) => `'${escape(a)}'`).join(', ')}] },`
    );

    const content = `/**
 * App permission sections. Used by role permission matrix and validation.
 * Generated by admin "Generate Section Enums" – do not edit by hand.
 */
export const SECTIONS = [
${lines.join('\n')}
] as const;

export type SectionId = (typeof SECTIONS)[number]['id'];

export const SECTION_IDS = SECTIONS.map((s) => s.id);

export function getSection(id: string) {
  return SECTIONS.find((s) => s.id === id);
}

export function isValidSection(id: string): boolean {
  return SECTIONS.some((s) => s.id === id || id === '*');
}
`;

    const filePath = path.join(process.cwd(), 'lib', 'sections.ts');
    await fs.writeFile(filePath, content, 'utf8');

    return NextResponse.json({ ok: true, message: 'Generated lib/sections.ts successfully' });
  } catch (e) {
    console.error('POST /api/admin/sections/generate-enums:', e);
    return NextResponse.json(
      { error: e instanceof Error ? e.message : 'Something went wrong' },
      { status: 500 }
    );
  }
}
