/**
 * App permission sections. Used by role permission matrix and validation.
 * Generated by admin "Generate Section Enums" – do not edit by hand.
 */
export const SECTIONS = [
  { id: 'companies', label: 'Companies', allowedActions: ['view', 'create', 'edit', 'delete', '*'] },
  { id: 'locations', label: 'Locations', allowedActions: ['view', 'create', 'edit', 'delete', '*'] },
  { id: 'roles', label: 'Roles', allowedActions: ['view', 'create', 'edit', 'delete', '*'] },
  { id: 'sections', label: 'Sections', allowedActions: ['view', 'create', 'edit', 'delete', '*'] },
  { id: 'teams', label: 'Teams', allowedActions: ['view', 'create', 'edit', 'delete', '*'] },
  { id: 'tickets', label: 'Tickets', allowedActions: ['view', 'create', 'edit', 'delete', 'assign', '*'] },
  { id: 'users', label: 'Users', allowedActions: ['view', 'create', 'edit', 'delete', '*'] },
] as const;

export type SectionId = (typeof SECTIONS)[number]['id'];

export const SECTION_IDS = SECTIONS.map((s) => s.id);

export function getSection(id: string) {
  return SECTIONS.find((s) => s.id === id);
}

export function isValidSection(id: string): boolean {
  return SECTIONS.some((s) => s.id === id || id === '*');
}
